# Generated by Django 3.2.17 on 2023-02-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Денежная сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('designation', models.CharField(max_length=3, unique=True, verbose_name='Обозначение')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bot.category')),
            ],
            options={
                'unique_together': {('title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='MessageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_value', models.CharField(max_length=255, verbose_name='Истинное значение в БД')),
                ('alias', models.CharField(max_length=255, verbose_name='Присвоенное значение')),
            ],
            options={
                'db_table': 'bot_message_map',
                'unique_together': {('db_value', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Денежная сумма')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bot.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('title', 'currency')},
        ),
    ]
