# Generated by Django 3.2.17 on 2023-02-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Денежная сумма')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения записи')),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='bot.account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='bot.account')),
            ],
        ),
    ]
