# Generated by Django 4.1.6 on 2023-02-13 15:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='amount',
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Сумма переведенная'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Сумма полученная'),
        ),
    ]
